// Code generated by raindrop build, DO NOT EDIT.
import { Ai, Annotation, App, KvCache, Logger, MRNObject, Tracer,  } from '@liquidmetal-ai/raindrop-framework';

export interface Env {
  _raindrop: {
    app: App;
  };
  AI: Ai;
  annotation: Annotation<Omit<MRNObject, 'type' | 'applicationName' | 'versionId'>>;
  ELEVENLABS_API_KEY: string;
  GROQ_API_KEY: string;
  logger: Logger;
  mem: KvCache;
  SERPAPI_KEY: string;
  tracer: Tracer;
}
